### REGISTER
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name": "test",
    "email": "test",
    "password": "test",
    "avatar_url": "test"
}

### LOGIN
POST http://localhost:3000/auth/login
Content-Type: application/json

{

    "email": "test",
    "password": "test"

}

### update user
PUT http://localhost:3000/auth/update/6
Content-Type: application/json

{
    "name": "Dovydelis",
    "email": "kazkoks@email.lt",
    "password": "1234567",
    "currentPassword": "123456",
    "avatar_url": "test"
}