### Get all ads
GET http://localhost:3000/api/ads

### Get one ad
GET http://localhost:3000/api/ads/1

### POST new ad
POST http://localhost:3000/api/ads
Content-Type: application/json

{
    "title": "Title",
    "main_img_url": 2,
    "description": 2,
    "price": 2,
    "phone": 2,
    "type": 2,
    "town_id": 2,
    "user_id": 2,
    "category_id": 2
}

### delete one ad
DELETE http://localhost:3000/api/ads/2


### get all towns
GET http://localhost:3000/api/towns

### get one town
GET http://localhost:3000/api/towns/1

### delete one town
DELETE http://localhost:3000/api/towns/1

### CREATE one town
POST http://localhost:3000/api/towns/
CONTENT-TYPE: application/json

{
    "name": "Kaunas",
    "population": 320000,
    "area": 157
}

### Random
delete http://localhost:3000/ok/towns/1